apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-fsx-ontap-nas
  namespace: trident
spec:
  version: 1
  backendName: fsx-ontap
  storageDriverName: ontap-nas
  managementLIF: [#replace with the Management DNS name for your svm management endpoint in FSxONTAP console]
  dataLIF: [#replace with the NFS DNS name for your svm NFS data endpoint in FSxONTAP console]
  svm: SVM1
  credentials:
    name: backend-fsx-ontap-nas-secret
